changelog:
  exclude:
    # 除外したいユーザー
    authors:
      - renovate
    # 除外したいlabel
    labels:
      - 🚫Ignore for release note
  categories:
    # 機能追加
    - title: ✨ New Features
      labels: '🔑Type: Feature✨'
    # バグフィックス
    - title: 🐛 Bug Fixes
      labels:
        - '🔑Type: Bug🐛'
    # パフォーマンス改善
    - title: 💹 Performance
      labels:
        - '🔑Type: Performance💹'
    # 破壊的変更
    - title: ⚠️Breaking Changes
    # CIやtest、リファクタリング、ビルド周りの整備等
    - title: 🔧 Maintenances
      labels:
        - '🔑Type: Document📝'
        - '🔑Type: Test💡'
        - '🔑Type: Refactoring♻️'
        - '🔑Type: Maintenance🔧'
    - title: 🖋️ Other Changes
      labels:
        - '*'