changelog:
  # リリースノートから除外したいユーザー
  exclude:
    authors:
      - renovate
  categories:
    # 機能追加、改善、改修
    - title: 💎 Enhancements
      labels:
        - enhancement
    # バグフィックス
    - title: 🐛 Bug Fix
      labels:
        - bug
    # CIやtest、リファクタリング、ビルド周りの整備等
    - title: Maintenance
      labels:
        - ci
        - test
        - refactoring
        - performance
    # ドキュメントの改善または追加
    - title: Documentation
      labels:
        - documentation
    - title: Breaking changes
      labels:
        - breaking change
    - title: 🖋️ Other Changes
      labels:
        - '*'