name: Create a release pull request

on:
  push:
    branches:
      # - main
      - "**"

jobs:
  create-release-tag:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TZ: "Asia/Tokyo"

    steps:
      - uses: actions/checkout@v3

      # 前回のリリースタグ取得
      - name: Get previous tag
        id: pre_tag
        run: |
          echo "::set-output name=pre_tag::$(curl -H 'Accept: application/vnd.github.v3+json' -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r .tag_name)"

